config/routes.rb
Plogress::Application.routes.draw do
  resources :users

  root to: 'tasks#index', as: 'tasks'
  resources :sessions

  post "tasks/create_new"
  post "subtasks/create_new"
  post "sessions/create_new"

  get "login/logout"

  get "login/start"

  get "register/start"

  get "main/view"

  post "login/login"

  post "register/register"

  resources :tasks

  resources :subtasks

end

app/models/task.rb
class Task < ActiveRecord::Base
  has_many :subtasks, dependent: :destroy
  belongs_to :user
  validates_inclusion_of :proficiency, :in => 0..4

  def duration
    dur = 0.0
    subtasks.each do |subtask|
      dur += subtask.duration
    end
    return dur.round(2)
  end

  def proficiency_level
    return ["None", "Bad", "Decent", "Good", "Proficient"]
  end

  def proficiency_to_s
    return proficiency_level[proficiency]
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
    @user_tasks = Task.find_all_by_user_id(session[:user].id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  def create_new
    @task = Task.create(:title => params[:title], :user_id => session[:user].id, :proficiency => params[:proficiency][:proficiency], :created => Time.now)
    redirect_to :action => 'index'
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
    access
  end

  def access
    if (session[:user].id != @task.user_id)
      flash[:error] = "You are not allowed to access this task."
      redirect_to tasks_path
      return false
    end
    return true
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])
    if (access)
      @task.proficiency = params[:proficiency][:proficiency]

      respond_to do |format|
        if @task.update_attributes(params[:task])
          format.html { redirect_to edit_task_path(@task), notice: 'Task was successfully updated.' }
          format.json { head :ok }
        else
          format.html { render action: "edit" }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    if (access)
      @task.destroy

      respond_to do |format|
        format.html { redirect_to tasks_url }
        format.json { head :ok }
      end
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="edit_stuff">
    <b><%= f.label 'Title: ' %> </b>
    <%= f.text_field :title %>

    <%= f.label :proficiency %>
        <% @selects = [['None', 0], ['Bad', 1], ['Decent', 2], ['Good', 3,], ['Proficient', 4]] %>
        <select id="proficiency_proficiency" name="proficiency[proficiency]">
          <% @selects.each do |item| %>
            <option value="<%= item[1] %>"
            <% if item[1] == @task.proficiency %>
               selected="selected"
            <% end %>
            >
            <%= item[0] %>
            </option>
          <% end %>
        </select>

    <%= f.submit 'Update' %>
  </div>

<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task: <%= @task.title %></h1>
<%= link_to 'Back to tasks', tasks_path %>


<table id="tasks">
  <tr>
    <td id="heading_task">Subtask</td>
    <td id="heading_time">Time</td>
    <td id="heading_subtask">Sessions</td>
    <td id="heading_prof">Proficiency</td>
    <td id="heading_manage"></td>
  </tr>
  <% Subtask.find_all_by_task_id(@task.id).each do |task| %>
      <tr>
        <td id="task"><%= task.title %></td>
        <td id="time"><%= task.duration %></td>
        <td id="subtask"><%= task.sessions.count %></td>
        <td id="prof"><%= task.proficiency_to_s %></td>
        <td id="manage"><%= link_to 'Manage', edit_subtask_path(task) %> <%= link_to 'X', task, confirm: 'Are you sure?', method: :delete %></td>
      </tr>
  <% end %>
  <tr>
    <%= form_tag({:controller => 'subtasks', :action => 'create_new'}, :method => "post") do %>
      <tr>
        <td colspan="5">&nbsp;</td>
      </tr>
      <td colspan="5">
        <%= hidden_field_tag(:task_id, @task.id) %>
        <%= label_tag(:title, "Title") %>
        <%= text_field_tag(:title) %>
        <%= label_tag(:proficiency, "Proficiency") %>
        <%= select(:proficiency, "proficiency", [['None', 0], ['Bad', 1], ['Decent', 2], ['Good', 3,], ['Proficient', 4]]) %>

        <%= submit_tag("Create new") %>
      </td>
      </tr>
  <% end %>
</table>
<br/>
<%= render 'form' %>  <br/>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>
<!--<p>User id:<%= session[:user].id %></p>-->

<table id="tasks">
  <tr>
    <td id="heading_task">Task</td>
    <td id="heading_time">Time</td>
    <td id="heading_subtask">Subtasks</td>
    <td id="heading_prof">Proficiency</td>
    <td id="heading_manage"></td>
  </tr>

  <% @user_tasks.each do |task| %>
      <tr>
        <td id="task"><%= task.title %></td>
        <td id="time"><%= task.duration %></td>
        <td id="subtask"><%= task.subtasks.count %></td>
        <td id="prof"><%= task.proficiency_to_s %></td>
        <td id="manage"><%= link_to 'Manage', edit_task_path(task) %> <%= link_to 'X', task, confirm: 'Are you sure?', method: :delete %></td>
      </tr>
  <% end %>
  <tr>
    <%= form_tag({:controller => 'tasks', :action => 'create_new'}, :method => "post") do %>
      <tr>
        <td colspan="5">&nbsp;</td>
      </tr>
      <td colspan="5">
        <%= label_tag(:title, "Title") %>
        <%= text_field_tag(:title) %>
        <%= label_tag(:proficiency, "Proficiency") %>
        <%= select(:proficiency, "proficiency", [['None', 0], ['Bad', 1], ['Decent', 2], ['Good', 3,], ['Proficient', 4]]) %>

        <%= submit_tag("Create new") %>
      </td>
      </tr>
  <% end %>
</table>
<br/>