config/routes.rb
Plogress::Application.routes.draw do
  resources :users

  root to: 'tasks#index', as: 'tasks'
  resources :sessions

  post "tasks/create_new"
  post "subtasks/create_new"
  post "sessions/create_new"

  get "login/logout"

  get "login/start"

  get "register/start"

  get "main/view"

  post "login/login"

  post "register/register"

  resources :tasks

  resources :subtasks

end

app/models/subtask.rb
class Subtask < ActiveRecord::Base
  belongs_to :task
  has_many :sessions, dependent: :destroy
  validates_inclusion_of :proficiency, :in => 0..4

  def proficiency_level
    return ["None", "Bad", "Decent", "Good", "Proficient"]
  end

  def proficiency_to_s
    return proficiency_level[proficiency]
  end

  def duration
    dur = 0.0
    sessions.each do |session|
      if (!session.duration.nil?)
        dur += session.duration
      end
    end
    return dur.round(2)
  end

  def proficiency_level
    return ["None", "Bad", "Decent", "Good", "Proficient"]
  end

  def proficiency_to_s
    return proficiency_level[proficiency]
  end

end

app/controllers/subtasks_controller.rb
class SubtasksController < ApplicationController

  def create_new
    task = Task.find(params[:task_id])
    Subtask.create(:title => params[:title], :proficiency => params[:proficiency][:proficiency], :task_id => task.id, :created => Time.now)
    redirect_to edit_task_path(task)
  end

  # GET /subtasks/1/edit
  def edit
    @subtask = Subtask.find(params[:id])
    @task = Task.find(@subtask.task_id)
    access
  end

  # PUT /subtasks/1
  # PUT /subtasks/1.json
  def update
    @subtask = Subtask.find(params[:id])
    if (access)
      @subtask.proficiency = params[:proficiency][:proficiency]

      respond_to do |format|
        if @subtask.update_attributes(params[:subtask])
          format.html { redirect_to edit_subtask_path(@subtask), notice: 'Subtask was successfully updated.' }
          format.json { head :ok }
        else
          format.html { render action: "edit" }
          format.json { render json: @subtask.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def access
    @task = Task.find(@subtask.task_id)
    if (session[:user].id != @task.user_id)
      flash[:error] = "You are not allowed to access this subtask."
      redirect_to tasks_path
      return false
    end
    return true
  end

  # DELETE /subtasks/1
  # DELETE /subtasks/1.json
  def destroy
    @subtask = Subtask.find(params[:id])
    if (access)
      task_id = @subtask.task_id
      @subtask.destroy
      task = Task.find(task_id)

      respond_to do |format|
        format.html { redirect_to edit_task_path(task) }
        format.json { head :ok }
      end
    end
  end
end

app/helpers/subtasks_helper.rb
module SubtasksHelper
end

app/views/subtasks/_form.html.erb
<%= form_for(@subtask) do |f| %>
  <% if @subtask.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subtask.errors.count, "error") %> prohibited this subtask from being saved:</h2>

      <ul>
      <% @subtask.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="edit_stuff">
    <%= f.hidden_field :task_id %>


    <b><%= f.label :title %></b>
    <%= f.text_field :title %>

    <%= f.label :proficiency %>
        <% @selects = [['None', 0], ['Bad', 1], ['Decent', 2], ['Good', 3,], ['Proficient', 4]] %>
        <select id="proficiency_proficiency" name="proficiency[proficiency]">
          <% @selects.each do |item| %>
            <option value="<%= item[1] %>"
            <% if item[1] == @subtask.proficiency %>
               selected="selected"
            <% end %>
            >
            <%= item[0] %>
            </option>
          <% end %>
        </select>

    <%= f.submit 'Update' %>
  </div>
<% end %>

app/views/subtasks/edit.html.erb
<h1>Editing subtask: <%= @subtask.title %></h1>
<%= link_to 'Back to task', edit_task_path(@task) %>

<table id="tasks">
  <tr>
    <td id="heading_task">Subtask</td>
    <td id="heading_time">&nbsp;</td>
    <td id="heading_subtask"></td>
    <td id="heading_subtask">Time</td>
    <td id="heading_prof"></td>

  </tr>
  <% Session.find_all_by_subtask_id(@subtask.id).each do |session| %>
      <tr>
        <td id="task" colspan="3"><%= session.description %></td>
        <td id="subtask"><%= session.duration %></td>
        <td id="prof"><%= link_to 'Manage', edit_session_path(session) %> <%= link_to 'X', session, confirm: 'Are you sure?', method: :delete %>
        </td>
      </tr>
  <% end %>
  <tr>
    <%= form_tag({:controller => 'sessions', :action => 'create_new'}, :method => "post") do %>
      <tr>
        <td colspan="5">&nbsp;</td>
      </tr>
      <td colspan="5">
        <%= hidden_field_tag(:subtask_id, @subtask.id) %>
        <b><%= label_tag(:description, "Description") %> </b><br>
        <%= text_area_tag :description, nil, :rows => 4, :cols => 68 %>
        <br>
        <%= label_tag(:duration, "Duration") %>
        <%= text_field_tag(:duration) %>

        <%= submit_tag("Create new") %>
        <br>

      </td>
      </tr>
  <% end %>
</table>

<br/>
<%= render 'form' %> <br/>